### ISSUE TITLE
Server patcher

### ISSUE THREAD

**Issue by samuelh2005** [MrLetsplay2003/ShittyAuthLauncher#1]
To be able to join servers with our custom accounts, we need to patch servers to. I have found some tools, but they are old and don't work. Maybe add a download server button to the launcher and it will patch the server's authlib to.

**Comment by samuelh2005** [comment]
On the server, the authlib is stored inside the server's jar

**Comment by samuelh2005** [comment]
@MrLetsplay2003 do you have any thoughts?

**Comment by MrLetsplay2003** [comment]
You should be able to play on a modern Minecraft server by setting the authentication server manually, e.g.
```
java -Dminecraft.api.auth.host=https://your.server -Dminecraft.api.account.host=https://your.server -Dminecraft.api.session.host=https://your.server -Dminecraft.api.services.host=https://your.server -jar server.jar
```
but I plan on making a patching tool that also supports older server versions as well, most likely in the form of a standalone CLI tool but maybe inside the launcher as well.

**Comment by samuelh2005** [comment]
Thank you.

**Comment by MrLetsplay2003** [comment]
A patching tool now exists (still in development but should mostly work): [ShittyAuthPatcher](https://github.com/MrLetsplay2003/ShittyAuthPatcher)

**Comment by samuelh2005** [comment]
Nice
