### ISSUE TITLE
Installations 

### ISSUE THREAD

**Issue by samuelh2005** [MrLetsplay2003/ShittyAuthLauncher#2]
We should have something like the vanilla launcher's installations tab, and a way to import vanilla installations, so we are able to easily run modded clients

**Comment by samuelh2005** [comment]
Can we have different session/auth servers for installations, so we don't have to change them if we need to join a server that needs different ones.

**Comment by MrLetsplay2003** [comment]
I'll take a look at that. It would probably mean that the launcher needs to be able to have multiple patched versions of the same authlib/Minecraft jars to be able to use different ones depending on the configured auth servers.

**Comment by samuelh2005** [comment]
In the vanilla launcher the installations are stored as (for windows) 
[```%appdata%\.minecraft\launcher_profiles.json```](https://github.com/MrLetsplay2003/ShittyAuthLauncher/files/8499777/launcher_profiles.txt), and has a format of the linked document, now we just need a way to import them

**Comment by MrLetsplay2003** [comment]
I just noticed that this issue is still open. I'm closing this issue as installations are implemented now
