### ISSUE TITLE
About the certificate error in #5

### ISSUE THREAD

**Issue by samuelh2005** [MrLetsplay2003/ShittyAuthLauncher#6]
From #5:
> 
> Are you using a self-signed certificate which your OS doesn't trust? Maybe you've added an exception in other places
> 
Actually, it's a Cloudflare origin server certificate. It is liked by web browsers and curl. Maybe Java cannot find Cloudflare's root certificate?
I will do a bit of testing eventually. Maybe I'll also ask Cloudflare about it.

**Comment by MrLetsplay2003** [comment]
That's strange. Cloudflare origin certificates are usually only used for communication between your server and Cloudflare and are thus often not trusted by default.

**Comment by samuelh2005** [comment]
All my website's traffic is proxied through Cloudflare. So, the web browsers see Cloudflare's certificate they have on their proxy.
Edit:
Then the Cloudflare proxy confirms the origin server's certificate.

**Comment by samuelh2005** [comment]
![image](https://user-images.githubusercontent.com/41990982/198023124-9db55feb-39c1-4449-a28f-05adc47f42c2.png)
![image](https://user-images.githubusercontent.com/41990982/198023324-10c5bfd0-13c5-4208-ad8d-cf7445460867.png)
![image](https://user-images.githubusercontent.com/41990982/198023396-8a871aad-0599-4aba-a15b-72c6bc680216.png)

The web browsers are all hunky dory.

**Comment by samuelh2005** [comment]
Here are the Cloudflare's SSL settings
![image](https://user-images.githubusercontent.com/41990982/198024210-f1f42bad-ccdd-467c-841a-9e8348431c84.png)

Since my origin server certificate is applied correctly, it must be something that Cloudflare has done with their certificate on their proxy.

**Comment by samuelh2005** [comment]
![image](https://user-images.githubusercontent.com/41990982/198027628-8207d71d-4ceb-4439-9cad-057b22d8a3dc.png)

Pinging my site would result with a Cloudflare IP address.
Edit
This would confirm that Cloudflare proxies the network traffic.

**Comment by MrLetsplay2003** [comment]
If the browser trusts it, Java should usually trust it as well. There are ways to manually import root certificates (described [here](https://stackoverflow.com/a/63491078/9870978)), but it's strange that your JRE/JDK would not trust Cloudflare by default.

Trying it on my end, everything appears to be fine and it doesn't throw any certificate errors when connecting (I'm running `openjdk version "17.0.4.1" 2022-08-12`)

**Comment by samuelh2005** [comment]
All fixed now! It actually was my authentication servers still using the old URL for my site (which still has certificate problems). Incorrect certificates on my old URL caused the error when the profile data was read.
